first=float(input('Enter the first number: '))
second=float(input('Enter the secong nubmer: '))
print(f'Sum: {first + second}')
print(f'Product: {first * second}')
print(f'Difference (1rst-2nd): {first - second}')
print(f'Difference (2nd-1rst): {second-first}')
quotient= first/second
print(f'Quotient (1rst:2nd): {quotient}')
print(f'Quotient (2nd:1rst): {second/first}')
input('Press ENTER to exit.')
